name: clean_generator
description: A simple command-line application for generating files to clean architecture apps.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

executables:
  clean_generator:

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies:
  args: ^2.2.0
